# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [ ]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [ ]:
A = np.arange(1, 16).reshape(3,5)

In [1]:
import numpy as np

A = np.arange(1, 16).reshape(3,5)

print("Dimension (number of axes):", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)

Dimension (number of axes): 2
Shape: (3, 5)
Size: 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

In [3]:
import numpy as np

B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

print("Matrix B:")
print(B)
print()
print("Matrix C:")
print(C)
print()

# Elementwise subtraction
elementwise_subtraction = B - C
print("Elementwise subtraction (B - C):")
print(elementwise_subtraction)
print()

# Elementwise multiplication
elementwise_multiplication = B * C
print("Elementwise multiplication (B * C):")
print(elementwise_multiplication)
print()

# Matrix multiplication
matrix_multiplication = B @ C
print("Matrix multiplication (B @ C):")
print(matrix_multiplication)

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise subtraction (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

In [4]:
import numpy as np

B = np.arange(1, 10).reshape(3, 3)
print("Matrix B:")
print(B)
print()

# Exponentiate each number elementwise
exp_B = np.exp(B)
print("Exponentiated B (elementwise):")
print(exp_B)
print()

# Calculate the minimum value in the whole matrix
min_value = np.min(B)
print("Minimum value in the whole matrix B:", min_value)
print()

# Calculate the minimum value in each row
min_value_row = np.min(B, axis=1)
print("Minimum value in each row:", min_value_row)
print()

# Calculate the minimum value in each column
min_value_col = np.min(B, axis=0)
print("Minimum value in each column:", min_value_col)
print()

# Find the index value for the minimum value in the whole matrix
min_index = np.argmin(B)
print("Index of the minimum value in the whole matrix:", min_index)
print()

# Find the index value for the minimum value in each row
min_index_row = np.argmin(B, axis=1)
print("Index of the minimum value in each row:", min_index_row)
print()

# Calculate the sum for all elements
sum_B = np.sum(B)
print("Sum of all elements:", sum_B)
print()

# Calculate the mean for each column
mean_col = np.mean(B, axis=0)
print("Mean for each column:", mean_col)
print()

# Calculate the median for each column
median_col = np.median(B, axis=0)
print("Median for each column:", median_col)

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiated B (elementwise):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the whole matrix B: 1

Minimum value in each row: [1 4 7]

Minimum value in each column: [1 2 3]

Index of the minimum value in the whole matrix: 0

Index of the minimum value in each row: [0 0 0]

Sum of all elements: 45

Mean for each column: [4. 5. 6.]

Median for each column: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [6]:
import numpy as np

A = np.arange(1, 16).reshape(3, 5)
print("Matrix A:")
print(A)
print()

sub_array = A[1]
print("A[1]:")
print(sub_array)

# In this example, A is a 2D array with shape (3, 5). 
# When you use A[1], you are selecting the entire second row of the matrix A. 
# The result is a 1D array containing all the elements of the second row.

Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

A[1]:
[ 6  7  8  9 10]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [ ]:
for i in A:
    print(i)

In [7]:
import numpy as np

A = np.arange(1, 16).reshape(3, 5)
print("Matrix A:")
print(A)
print()

print("Elementwise iteration")
for element in np.nditer(A):
    print(element)

Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Elementwise iteration
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

In [8]:
import numpy as np

a = np.arange(30)
b = a.reshape((2, 3, -1))
print("Array a:")
print(a)
print()

print("Array b:")
print(b)

Array a:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

Array b:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# 1. We create a 1D array a with 30 elements using np.arange(30).
#     a = np.arange(30)
# 2. We reshape the 1D array a into a 3D array b with shape (2, 3, -1).
#     b = a.reshape((2, 3, -1))

# 3. The -1 in the reshape function is a placeholder that tells NumPy to automatically calculate,
#     the size of the third dimension based on the total number of elements in the array. 
#     In this case, since a has 30 elements and we are reshaping it into a (2, 3, -1) array, 
#     the third dimension will be calculated as 5 (30 / (2*3)).

#         print(a)
#         print()
#         print(b)

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [9]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):
    # Validate that the inputs are of type numpy.ndarray
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise TypeError("Both inputs must be of type numpy.ndarray")

# Validate that the operation is either 'add' or 'multiply'
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation must be either 'add' or 'multiply'")

    if operation == 'add':
        # Validate that the matrices have the same size for addition
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same shape for addition")
        return matrix1 + matrix2

    elif operation == 'multiply':
        # Validate that the sizes conform for matrix multiplication
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the secons matrix for multiplication")
        return matrix1 @ matrix2

# Example usage
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Addition
result_add = add_mult_matrices(matrix1, matrix2, 'add')
print("Addition result:")
print(result_add)
print()

# Multiplication
result_mult = add_mult_matrices(matrix1, matrix2, 'multiply')
print("Multiplication result:")
print(result_mult)

Addition result:
[[ 6  8]
 [10 12]]

Multiplication result:
[[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [10]:
import numpy as np

# Define the vector x
x = np.array([4, 3])

# (a) Dimension of vector x
dimension_x = x.shape
print("Dimension of vector x:", dimension_x)

# (b) Calculate 5x
five_x = 5 * x
print("5x:", five_x)

# (c) Calculate 3x
three_x = 3 * x
print("3x:", three_x)

# (d) Calculate 5x + 3x
five_x_plus_three_x = 5 * x + 3 * x
print("5x + 3x:", five_x_plus_three_x)

# (e) Calculate 8x
eight_x = 8 * x
print("8x:", eight_x)

# (f) Calculate 4x - x
four_x_minus_x = 4 * x - x
print("4x - x:", four_x_minus_x)

# (g) Calculate x transpose and its new dimension
x_transpose = x.reshape(-1, 1)
dimension_x_transpose = x_transpose.shape
print("x transpose:\n", x_transpose)
print("Dimension of x transpose:", dimension_x_transpose)

# (h) Is x + x transpose defined?
# x is a 1D array and x transpose is a 2D array, so x + x transpose is not defined
is_defined = False
print("Is x + x transpose defined?", is_defined)

# (i) Calculate the norm of x
norm_x = np.linalg.norm(x)
print("Norm of x:", norm_x)

Dimension of vector x: (2,)
5x: [20 15]
3x: [12  9]
5x + 3x: [32 24]
8x: [32 24]
4x - x: [12  9]
x transpose:
 [[4]
 [3]]
Dimension of x transpose: (2, 1)
Is x + x transpose defined? False
Norm of x: 5.0


In [11]:
import numpy as np

# Define the vector v
v = np.array([3, 7, 0, 11])

# (a) Dimension of vector v
dimension_v = v.shape
print("Dimension of vector v:", dimension_v)

# (b) Calculate 2v
two_v = 2 * v
print("2v:", two_v)

# (c) Calculate 5v + 2v
five_v_plus_two_v = 5 * v + 2 * v
print("5v + 2v:", five_v_plus_two_v)

# (d) Calculate 4v - 2v
four_v_minus_two_v = 4 * v - 2 * v
print("4v - 2v:", four_v_minus_two_v)

# (e) Calculate v transpose and its new dimension
v_transpose = v.reshape(-1, 1)
dimension_v_transpose = v_transpose.shape
print("v transpose:\n", v_transpose)
print("Dimension of v transpose:", dimension_v_transpose)

# (f) Calculate the norm of v
norm_v = np.linalg.norm(v)
print("Norm of v:", norm_v)

Dimension of vector v: (4,)
2v: [ 6 14  0 22]
5v + 2v: [21 49  0 77]
4v - 2v: [ 6 14  0 22]
v transpose:
 [[ 3]
 [ 7]
 [ 0]
 [11]]
Dimension of v transpose: (4, 1)
Norm of v: 13.379088160259652


In [12]:
import numpy as np

# Define the vectors v1 and v2
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# (a) Calculate the norm of v1
norm_v1 = np.linalg.norm(v1)
print("Norm of v1:", norm_v1)

# (b) Calculate the norm of v1 - v2
norm_v1_minus_v2 = np.linalg.norm(v1 - v2)
print("Norm of v1 - v2:", norm_v1_minus_v2)

Norm of v1: 7.14142842854285
Norm of v1 - v2: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [ ]:
import numpy as np

# Define the coefficient matrix A
A = np.array([
    [3, 2, 4],
    [2, 3, 8],
    [4, 1, 3],
    [7, 1, 5]
])

# Define the constants vector b
b = np.array([7, 4, 11, 9])

# Define the solution vector x (assuming we have already solved for x)
# For demonstration purposes, let's assume x is the solution we found
x = np.linalg.solve(A, b)

# Verify the solution by performing the matrix multiplication Ax
Ax = A @ x

print("Matrix A:")
print(A)
print()
print("Vector b:")
print(b)
print()
print("Solution vector x:")
print(x)
print()
print("Matrix multiplication Ax:")
print(Ax)
print()
print("Verification (Ax == b):")
print(np.allclose(Ax, b))

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [13]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[4 3 1 5]
[  2   3   1 123]


In [ ]:
# The .base attribute of an array points to the original array if the array is a view. Otherwise, .base is None for a copy.

# # Output:
# v1.base is None because v1 is the original array.
# v2.base is not None and will point to v1, confirming that v2 is a view of v1.

# v2[-1] refers to the last element of v2, which corresponds to the last element of the slice 
# v1[-1].
# Modifying this element in v2 also modifies the corresponding element in v1 because they share the same data buffer.

# # Output:
#     # After modification:
#         v1: [0, 1, 2, 123]
#         v2: [2, 123]